---
apiVersion: v1
kind: Service
metadata:
  name: redis-deployment-service
  labels:
    name: redis-deployment-service
    author: gina
spec:
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    matchLabels:
      name: redis-deployment
...