---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    author: gina
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-deployment
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-deployment
    spec:
      containers:
        - name: myredis
          image: redis
          ports:
            - containerPort: 6379
...