apiVersion: v1
kind: Pod
metadata:
 name: result-app-pod
 labels:
  name: result-app-pod
  author: gina
spec:
 containers:
  - name: result-app
    image: dockersamples/examplevotingapp_result
    ports:
     - containerPorts: 80
...