---
apiVersion: v1
kind: Service
metadata:
  name: result-app-deployment-service
  labels:
    name: result-app-deployment-service
    author: gina
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    matchLabels:
      name: result-app-deployment
...