---
apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    author: gina
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_worker
      ports:
        - containerPort: 80
...