---
apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    author: gina
spec:
  containers:
    - name: worker-app
      image: dockersampels/examplevotingapp_worker
...